% 
% CBS SPM preprocessing batch package -- Template Overwrite Script
% Created by Caitlin Carey
%
% This script overwrites filler variables generated by the template script.
%
%--------------------------------------------------------------------------

fprintf('Overwriting template preproc batch for %s %s\n',type,subject);

% these are taken from input
subjectNum = subject;
directoryPre = directory;
taskDir = task;
subjectType = type;

% creates subject directory path
if (strcmp(subjectType,'NONE'))
    subjectDir = [directoryPre, subjectNum, '/'];
else
    subjectDir = [directoryPre, type, '/', subjectNum, '/'];
end

% determines number of runs
runs = length(dir([subjectDir,taskDir, 'run*']));

% grabs correct structural file for subject
try 
    fprintf('Grabbing structurals from %s.\n', [subjectDir, 'structural/']);
    % need to figure out why nodisplay and display treat this differently
    try 
        % need to figure out a way around using 's1*'
        structFilelist = strtrim(ls([subjectDir,'structural/s1*176*.img']));
        structFilelist = regexp(structFilelist,'\n','split');
        structFile = char(structFilelist(2));    
    catch
        structFilelist = strtrim(ls([subjectDir,'structural/s1*176*.img']));
        structFilelist = regexp(structFilelist,' ','split');
        structFile = char(structFilelist(3));
    end
catch 
    fprintf('Could not locate structurals in %s.\n', [subjectDir, 'structural/']);
    rethrow(lasterror());
    
end
    
%--------------------------------------------------------------------------

% here i'm not sure if the batch numbers change...so we might need to
% finagle this a bit more

% if we dont have the correct number of runs, throw error
if (length(matlabbatch{1}.spm.spatial.realign.estwrite.data) ~= runs)
    error('TestRuns:WrongNum','Subject does not have expected number of runs.');
end 

% creates structure of epis for each run
for i = 1:runs
    try
        fprintf('Grabbing functionals from %s.\n', [subjectDir, taskDir, 'run', num2str(i), '/']);
        epis = strtrim(ls([subjectDir, taskDir, 'run', num2str(i), '/f*.img']));
    catch
        fprintf('Could not locate functionals in %s.\n', [subjectDir, taskDir, 'run', num2str(i), '/']);
        rethrow(lasterror());
    end

    % checks that we have the correct number of epis
    originallen = length(matlabbatch{1}.spm.spatial.realign.estwrite.data{i});
    functionals = regexp(epis,'\n','split')';

    % if not, throw error
    if (length(functionals) ~= originallen)
        error('TestEpis:WrongNum','Subject does not have expected number of epis.');
    end

    % if so, replace template epis
    matlabbatch{1}.spm.spatial.realign.estwrite.data{i} = functionals;

end

% grabs structural file for coreg
matlabbatch{2}.spm.spatial.coreg.estimate.source = {[structFile,',1']};

% grabs structural file for preproc
matlabbatch{3}.spm.spatial.preproc.data = {[structFile,',1']};
